=== NickDraper/SpinWaveGenie/examples/SpinWaveGenieSchema.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="SpinWaveGenieSchema" elementFormDefault="qualified" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:swg="SpinWaveGenieSchema">
    <xsd:complexType name="SublatticeType">
    	<xsd:all>
    		<xsd:element name="name" type="xsd:string" minOccurs="1"
    			maxOccurs="1">
    		</xsd:element>
    		<xsd:element name="moment" type="swg:MomentType"
    			maxOccurs="1" minOccurs="1">
    		</xsd:element>
    		<xsd:element name="atomicpositions" maxOccurs="1" minOccurs="1">
    			<xsd:complexType>
    				<xsd:sequence>
    					<xsd:element name="position"
    						type="swg:PositionType" maxOccurs="unbounded" minOccurs="1">
    					</xsd:element>
    				</xsd:sequence>
    			</xsd:complexType>
    		</xsd:element>
    	</xsd:all>
    </xsd:complexType>

    <xsd:complexType name="MomentType">
    	<xsd:all>
    		<xsd:element name="magnitude" type="xsd:double" maxOccurs="1" minOccurs="1">
    		</xsd:element>
    		<xsd:element name="theta" type="xsd:double" maxOccurs="1" minOccurs="1"></xsd:element>
    		<xsd:element name="phi" maxOccurs="1" minOccurs="1" type="xsd:double">
    		</xsd:element>
    	</xsd:all>
    </xsd:complexType>

    <xsd:complexType name="PositionType">
    	<xsd:all>
    		<xsd:element name="x" type="xsd:double"></xsd:element>
    		<xsd:element name="y" type="xsd:double"></xsd:element>
    		<xsd:element name="z" type="xsd:double"></xsd:element>
    	</xsd:all>
    </xsd:complexType>


    <xsd:complexType name="ExchangeType">
    	<xsd:all>
    		<xsd:element name="value" type="xsd:double" maxOccurs="1"
    			minOccurs="1">
    		</xsd:element>
    		<xsd:element name="mindist" type="xsd:double" maxOccurs="1"
    			minOccurs="1">
    		</xsd:element>
    		<xsd:element name="maxdist" type="xsd:double" maxOccurs="1"
    			minOccurs="1">
    		</xsd:element>
    		<xsd:element name="pairs" maxOccurs="1" minOccurs="1">
    			<xsd:complexType>
    				<xsd:sequence>
    					<xsd:element name="pair" type="swg:PairType" maxOccurs="unbounded" minOccurs="1">
    					</xsd:element>
    				</xsd:sequence>
    			</xsd:complexType>
    		</xsd:element>
    	</xsd:all>
    </xsd:complexType>
    
    <xsd:complexType name="AnisotropyType">
    	<xsd:all>
    		<xsd:element name="value" type="xsd:double" maxOccurs="1"
    			minOccurs="1">
    		</xsd:element>
    		<xsd:element name="direction" type="swg:PositionType" maxOccurs="1" minOccurs="1"></xsd:element>
    		<xsd:element name="sublattices">
    			<xsd:complexType>
    				<xsd:sequence>
    					<xsd:element name="name" type="xsd:string"
    						maxOccurs="unbounded" minOccurs="1">
    					</xsd:element>
    				</xsd:sequence>
    			</xsd:complexType>
    		</xsd:element>
    	</xsd:all>
    </xsd:complexType>


    <xsd:complexType name="CellType">
    	<xsd:all>
    		<xsd:element name="latticevectors"
    			type="swg:LatticeVectorsType" maxOccurs="1" minOccurs="1">
    		</xsd:element>
    		<xsd:element name="moments" maxOccurs="1" minOccurs="1">
    			<xsd:complexType>
    				<xsd:sequence>
    					<xsd:element name="sublattice"
    						type="swg:SublatticeType" maxOccurs="unbounded" minOccurs="1">
    					</xsd:element>
    				</xsd:sequence>
    			</xsd:complexType></xsd:element>
    	</xsd:all>
    </xsd:complexType>

    <xsd:complexType name="LatticeVectorsType">
    	<xsd:all>
    		<xsd:element name="a" maxOccurs="1" minOccurs="1">
    			<xsd:simpleType>
    				<xsd:restriction base="xsd:double">
    					<xsd:minExclusive value="0.0"></xsd:minExclusive>
    				</xsd:restriction>
    			</xsd:simpleType>
    		</xsd:element>
    		<xsd:element name="b" maxOccurs="1" minOccurs="1">
    			<xsd:simpleType>
    				<xsd:restriction base="xsd:double">
    					<xsd:minExclusive value="0.0"></xsd:minExclusive>
    				</xsd:restriction>
    			</xsd:simpleType>
    		</xsd:element>
    		<xsd:element name="c" maxOccurs="1" minOccurs="1">
    			<xsd:simpleType>
    				<xsd:restriction base="xsd:double">
    					<xsd:minExclusive value="0.0"></xsd:minExclusive>
    				</xsd:restriction>
    			</xsd:simpleType>
    		</xsd:element>
    		<xsd:element name="alpha" maxOccurs="1" minOccurs="1">
    			<xsd:simpleType>
    				<xsd:restriction base="xsd:double">
    					<xsd:minInclusive value="0.0"></xsd:minInclusive>
    					<xsd:maxInclusive value="360.0"></xsd:maxInclusive>
    				</xsd:restriction>
    			</xsd:simpleType>
    		</xsd:element>
    		<xsd:element name="beta" maxOccurs="1" minOccurs="1">
    			<xsd:simpleType>
    				<xsd:restriction base="xsd:double">
    					<xsd:maxInclusive value="360.0"></xsd:maxInclusive>
    					<xsd:minInclusive value="0"></xsd:minInclusive>
    				</xsd:restriction>
    			</xsd:simpleType>
    		</xsd:element>
    		<xsd:element name="gamma" maxOccurs="1" minOccurs="1">
    			<xsd:simpleType>
    				<xsd:restriction base="xsd:double">
    					<xsd:maxInclusive value="360"></xsd:maxInclusive>
    					<xsd:minInclusive value="0"></xsd:minInclusive>
    				</xsd:restriction>
    			</xsd:simpleType>
    		</xsd:element>
    	</xsd:all>
    </xsd:complexType>

    <xsd:complexType name="InteractionsType">
    	<xsd:all>
    		<xsd:element name="Anisotropy"
    			type="swg:AnisotropyGroupType" maxOccurs="1" minOccurs="0">
    		</xsd:element>
    		<xsd:element name="Exchange" type="swg:ExchangeGroupType"
    			maxOccurs="1" minOccurs="0">
    		</xsd:element>
    	</xsd:all>
    </xsd:complexType>


    <xsd:element name="spinwavegenie">
    	<xsd:complexType>
    		<xsd:all>
    			<xsd:element name="cell" type="swg:CellType" maxOccurs="1" minOccurs="1"></xsd:element>
    			<xsd:element name="interactions"
    				type="swg:InteractionsType" maxOccurs="1" minOccurs="1">
    			</xsd:element>
    		</xsd:all>
    	</xsd:complexType></xsd:element>

    <xsd:complexType name="PairType">
    	<xsd:all>
    		<xsd:element name="name1" type="xsd:string" maxOccurs="1" minOccurs="1"></xsd:element>
    		<xsd:element name="name2" type="xsd:string" maxOccurs="1" minOccurs="1"></xsd:element>
    	</xsd:all>
    </xsd:complexType>

    <xsd:complexType name="AnisotropyGroupType">
    	<xsd:sequence>
    		<xsd:element name="group" type="swg:AnisotropyType" maxOccurs="unbounded" minOccurs="1"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="ExchangeGroupType">
    	<xsd:sequence>
    		<xsd:element name="group" type="swg:ExchangeType" maxOccurs="unbounded" minOccurs="1"></xsd:element>
    	</xsd:sequence>
    </xsd:complexType>
</xsd:schema>

=== NickDraper/SpinWaveGenie/examples/old/YFeO3TwoSublattice.xml
<?xml version="1.0" encoding="UTF-8"?>
<spinwavegenie xmlns="SpinWaveGenieSchema" xmlns:swg="http://www.example.org/SpinWaveGenieSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="SpinWaveGenieSchema SpinWaveGenieSchema.xsd ">
  <cell>
    <latticevectors>
      <a>5.0</a>
      <b>5.0</b>
      <c>7.071</c>
      <alpha>90.0</alpha>
      <beta>90.0</beta>
      <gamma>90.0</gamma>
    </latticevectors>
    <moments>
      <sublattice>
        <name>Fe1</name>
        <type>FE3</type>
        <moment>
          <magnitude>2.5</magnitude>
          <theta>90.0</theta>
          <phi>180.0</phi>
        </moment>
        <atomicpositions>
          <position>
            <x>0.0</x>
            <y>0.5</y>
            <z>0.5</z>
          </position>
          <position>
      	    <x>0.5</x>
      	    <y>0.0</y>
      	    <z>0.0</z>
          </position>
        </atomicpositions>
      </sublattice>
      <sublattice>
        <name>Fe2</name>
        <type>FE3</type>
        <moment>
          <magnitude>2.5</magnitude>
          <theta>90.0</theta>
          <phi>0.0</phi>
        </moment>
        <atomicpositions>
          <position>
            <x>0.0</x>
            <y>0.5</y>
            <z>0.0</z>
          </position>
          <position>
      	    <x>0.5</x>
      	    <y>0.0</y>
      	    <z>0.5</z>
          </position>
        </atomicpositions>
      </sublattice>
    </moments>    
  </cell>
  <interactions>
    <Anisotropy>
      <group>
        <direction>
          <x>1.0</x>
          <y>0.0</y>
          <z>0.0</z>
        </direction>
        <value>-0.0046</value>
    	<sublattices>
    	  <name>Fe1</name>
    	  <name>Fe2</name>
    	</sublattices>
      </group>
      <group>
        <direction>
          <x>0.0</x>
          <y>0.0</y>
          <z>1.0</z>
        </direction>
        <value>-0.0013</value>
    	<sublattices>
    	  <name>Fe1</name>
    	  <name>Fe2</name>
    	</sublattices>
      </group>        	
    </Anisotropy>   
    <Exchange>
        <group>
            <value>-4.2</value>
            <mindist>3.5</mindist>
            <maxdist>4.0</maxdist>
            <pairs>
                <pair><name1>Fe1</name1><name2>Fe2</name2></pair>
            </pairs>
        </group>
    </Exchange>
  </interactions>
</spinwavegenie>

=== NickDraper/SpinWaveGenie/MnV2O4/exchange/MnV2O4_JBB_9p5.xml
<?xml version="1.0" encoding="UTF-8"?>
<spinwavegenie xmlns:swg="SpinWaveGenieSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="SpinWaveGenieSchema SpinWaveGenieSchema.xsd ">
  <cell>
    <latticevectors>
      <a>6.0104</a>
      <b>6.0104</b>
      <c>8.5</c>
      <alpha>90.0</alpha>
      <beta>90.0</beta>
      <gamma>90.0</gamma>
    </latticevectors>
    <moments>
      <sublattice>
        <name>Mn0</name>
        <type>MN2</type>
        <moment>
          <magnitude>2.5</magnitude>
          <theta>0.0</theta>
          <phi>0.0</phi>
        </moment>
        <atomicpositions>
          <position>
            <x>0.0</x>
            <y>0.25</y>
            <z>0.125</z>
          </position>
          <position>
          	<x>0.5</x>
          	<y>0.75</y>
          	<z>0.625</z>
          </position>
        </atomicpositions>
      </sublattice>
      <sublattice>
      	<name>Mn1</name>
      	<type>MN2</type>
      	<moment>
      		<magnitude>2.5</magnitude>
      		<theta>0.0</theta>
      		<phi>0.0</phi>
      	</moment>
      	<atomicpositions>
      		<position>
      			<x>0.5</x>
      			<y>0.25</y>
      			<z>0.375</z>
      		</position>
      		<position>
      			<x>0.0</x>
      			<y>0.75</y>
      			<z>0.875</z>
      		</position>
      	</atomicpositions>
      </sublattice>
      <sublattice>
      	<name>V0</name>
      	<type>V3</type>
      	<moment>
      		<magnitude>1.0</magnitude>
      		<theta>116.271355853</theta>
      		<phi>270.0</phi>
      	</moment>
      	<atomicpositions>
      		<position>
      			<x>0.0</x>
      			<y>0.0</y>
      			<z>0.5</z>
      		</position>
      		<position>
      			<x>0.5</x>
      			<y>0.5</y>
      			<z>0.0</z>
      		</position>
      	</atomicpositions>
      </sublattice>
      <sublattice>
      	<name>V1</name>
      	<type>V3</type>
      	<moment>
      		<magnitude>1.0</magnitude>
      		<theta>116.271355853</theta>
      		<phi>0.0</phi>
      	</moment>
      	<atomicpositions>
      		<position>
      			<x>0.75</x>
      			<y>0.25</y>
      			<z>0.75</z>
      		</position>
      		<position>
      			<x>0.25</x>
      			<y>0.75</y>
      			<z>0.25</z>
      		</position>
      	</atomicpositions>
      </sublattice>
      <sublattice>
      	<name>V2</name>
      	<type>V3</type>
      	<moment>
      		<magnitude>1.0</magnitude>
      		<theta>116.271355853</theta>
      		<phi>90.0</phi>
      	</moment>
      	<atomicpositions>
      		<position>
      			<x>0.5</x>
      			<y>0.0</y>
      			<z>0.0</z>
      		</position>
      		<position>
      			<x>0.0</x>
      			<y>0.5</y>
      			<z>0.5</z>
      		</position>
      	</atomicpositions>
      </sublattice>
      <sublattice>
      	<name>V3</name>
      	<type>V3</type>
      	<moment>
      		<magnitude>1.0</magnitude>
      		<theta>116.271355853</theta>
      		<phi>180.0</phi>
      	</moment>
      	<atomicpositions>
      		<position>
      			<x>0.75</x>
      			<y>0.75</y>
      			<z>0.25</z>
      		</position>
      		<position>
      			<x>0.25</x>
      			<y>0.25</y>
      			<z>0.75</z>
      		</position>
      	</atomicpositions>
      </sublattice>
    </moments>
  </cell>
  <interactions>
  	<Exchange>
  		<group>
  			<value>-1.8</value>
  			<mindist>3.48</mindist>
  			<maxdist>3.57</maxdist>
  			<pairs>
  				<pair>
  					<name1>Mn0</name1>
  					<name2>V0</name2>
  				</pair>
  				<pair>
  					<name1>Mn0</name1>
  					<name2>V1</name2>
  				</pair>
  				<pair>
  					<name1>Mn0</name1>
  					<name2>V2</name2>
  				</pair>
  				<pair>
  					<name1>Mn0</name1>
  					<name2>V3</name2>
  				</pair>
  				<pair>
  					<name1>Mn1</name1>
  					<name2>V0</name2>
  				</pair>
  				<pair>
  					<name1>Mn1</name1>
  					<name2>V1</name2>
  				</pair>
  				<pair>
  					<name1>Mn1</name1>
  					<name2>V2</name2>
  				</pair>
  				<pair>
  					<name1>Mn1</name1>
  					<name2>V3</name2>
  				</pair>
  			</pairs>
  		</group>
  		<group>
  			<value>-9.5</value>
  			<mindist>2.975</mindist>
  			<maxdist>3.06</maxdist>
  			<pairs>
  				<pair>
  					<name1>V0</name1>
  					<name2>V2</name2>
  				</pair>
  				<pair>
  					<name1>V1</name1>
  					<name2>V3</name2>
  				</pair>
  			</pairs>
  		</group>
  		<group>
  			<value>-3.0</value>
  			<mindist>2.975</mindist>
  			<maxdist>3.06</maxdist>
  			<pairs>
  				<pair>
  					<name1>V0</name1>
  					<name2>V1</name2>
  				</pair>
  				<pair>
  					<name1>V0</name1>
  					<name2>V3</name2>
  				</pair>
  				<pair>
  					<name1>V2</name1>
  					<name2>V1</name2>
  				</pair>
  				<pair>
  					<name1>V2</name1>
  					<name2>V3</name2>
  				</pair>
  			</pairs>
  		</group>
  	</Exchange>
  	<Anisotropy>
  		<group>
  			<value>-0.1</value>
  			<direction>
  				<x>0.0</x>
  				<y>0.0</y>
  				<z>1.0</z>
  			</direction>
  			<sublattices>
  				<name>Mn0</name>
  				<name>Mn1</name>
  			</sublattices>
  		</group>
  		<group>
  			<value>0.7</value>
  			<direction>
  				<x>0.0</x>
  				<y>0.0</y>
  				<z>1.0</z>
  			</direction>
  			<sublattices>
  				<name>V0</name>
  				<name>V1</name>
  				<name>V2</name>
  				<name>V3</name>
  			</sublattices>
  		</group>
  		<group>
  			<value>-4.8</value>
  			<direction>
  				<x>1.0</x>
  				<y>0.0</y>
  				<z>0.0</z>
  			</direction>
  			<sublattices>
  				<name>V1</name>
  				<name>V3</name>
  			</sublattices>
  		</group>
  		<group>
  			<value>-4.8</value>
  			<direction>
  				<x>0.0</x>
  				<y>1.0</y>
  				<z>0.0</z>
  			</direction>
  			<sublattices>
  				<name>V0</name>
  				<name>V2</name>
  			</sublattices>
  		</group>
  	</Anisotropy>
  </interactions>
</spinwavegenie>

=== NickDraper/SpinWaveGenie/examples/MnV2O4_111.xml
<?xml version="1.0" encoding="UTF-8"?>
<spinwavegenie xmlns="SpinWaveGenieSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="SpinWaveGenieSchema SpinWaveGenieSchema.xsd ">
  <cell>
    <latticevectors>
      <a>6.0104</a>
      <b>6.0104</b>
      <c>8.5</c>
      <alpha>90.0</alpha>
      <beta>90.0</beta>
      <gamma>90.0</gamma>
    </latticevectors>
    <moments>
      <sublattice>
        <name>Mn0</name>
        <type>MN2</type>
        <moment>
          <magnitude>2.5</magnitude>
          <theta>0.0</theta>
          <phi>0.0</phi>
        </moment>
        <atomicpositions>
          <position>
            <x>0.0</x>
            <y>0.25</y>
            <z>0.125</z>
          </position>
          <position>
          	<x>0.5</x>
          	<y>0.75</y>
          	<z>0.625</z>
          </position>
        </atomicpositions>
      </sublattice>
      <sublattice>
      	<name>Mn1</name>
      	<type>MN2</type>
      	<moment>
      		<magnitude>2.5</magnitude>
      		<theta>0.0</theta>
      		<phi>0.0</phi>
      	</moment>
      	<atomicpositions>
      		<position>
      			<x>0.5</x>
      			<y>0.25</y>
      			<z>0.375</z>
      		</position>
      		<position>
      			<x>0.0</x>
      			<y>0.75</y>
      			<z>0.875</z>
      		</position>
      	</atomicpositions>
      </sublattice>
      <sublattice>
      	<name>V0</name>
      	<type>V3</type>
      	<moment>
      		<magnitude>1.0</magnitude>
      		<theta>145.0</theta>
      		<phi>270.0</phi>
      	</moment>
      	<atomicpositions>
      		<position>
      			<x>0.0</x>
      			<y>0.0</y>
      			<z>0.5</z>
      		</position>
      		<position>
      			<x>0.5</x>
      			<y>0.5</y>
      			<z>0.0</z>
      		</position>
      	</atomicpositions>
      </sublattice>
      <sublattice>
      	<name>V1</name>
      	<type>V3</type>
      	<moment>
      		<magnitude>1.0</magnitude>
      		<theta>145.0</theta>
      		<phi>0.0</phi>
      	</moment>
      	<atomicpositions>
      		<position>
      			<x>0.75</x>
      			<y>0.25</y>
      			<z>0.75</z>
      		</position>
      		<position>
      			<x>0.25</x>
      			<y>0.75</y>
      			<z>0.25</z>
      		</position>
      	</atomicpositions>
      </sublattice>
      <sublattice>
      	<name>V2</name>
      	<type>V3</type>
      	<moment>
      		<magnitude>1.0</magnitude>
      		<theta>145.0</theta>
      		<phi>90.0</phi>
      	</moment>
      	<atomicpositions>
      		<position>
      			<x>0.5</x>
      			<y>0.0</y>
      			<z>0.0</z>
      		</position>
      		<position>
      			<x>0.0</x>
      			<y>0.5</y>
      			<z>0.5</z>
      		</position>
      	</atomicpositions>
      </sublattice>
      <sublattice>
      	<name>V3</name>
      	<type>V3</type>
      	<moment>
      		<magnitude>1.0</magnitude>
      		<theta>145.0</theta>
      		<phi>180.0</phi>
      	</moment>
      	<atomicpositions>
      		<position>
      			<x>0.75</x>
      			<y>0.75</y>
      			<z>0.25</z>
      		</position>
      		<position>
      			<x>0.25</x>
      			<y>0.25</y>
      			<z>0.75</z>
      		</position>
      	</atomicpositions>
      </sublattice>
    </moments>
  </cell>
  <interactions>
  	<Exchange>
        <group>
            <name>Jaa</name>
  			<value>-0.2</value>
  			<mindist>3.65</mindist>
  			<maxdist>3.7</maxdist>
  			<pairs>
  				<pair>
  					<name1>Mn0</name1>
  					<name2>Mn1</name2>
  				</pair>
  			</pairs>
  		</group>
        <group>
            <name>Jab</name>
            <value>-2.0</value>
            <mindist>3.48</mindist>
            <maxdist>3.57</maxdist>
            <pairs>
                <pair>
                    <name1>Mn0</name1>
                    <name2>V0</name2>
                </pair>
                <pair>
                    <name1>Mn0</name1>
                    <name2>V1</name2>
                </pair>
                <pair>
                    <name1>Mn0</name1>
                    <name2>V2</name2>
                </pair>
                <pair>
                    <name1>Mn0</name1>
                    <name2>V3</name2>
                </pair>
                <pair>
                    <name1>Mn1</name1>
                    <name2>V0</name2>
                </pair>
                <pair>
                    <name1>Mn1</name1>
                    <name2>V1</name2>
                </pair>
                <pair>
                    <name1>Mn1</name1>
                    <name2>V2</name2>
                </pair>
                <pair>
                    <name1>Mn1</name1>
                    <name2>V3</name2>
                </pair>
            </pairs>
        </group>
        <group>
            <name>Jbb</name>
            <value>-10.0</value>
            <mindist>2.975</mindist>
            <maxdist>3.06</maxdist>
            <pairs>
                <pair>
                    <name1>V0</name1>
                    <name2>V2</name2>
                </pair>
                <pair>
                    <name1>V1</name1>
                    <name2>V3</name2>
                </pair>
            </pairs>
        </group>
        <group>
            <name>Jbbp</name>
            <value>2.0</value>
            <mindist>2.975</mindist>
            <maxdist>3.06</maxdist>
            <pairs>
                <pair>
                    <name1>V0</name1>
                    <name2>V1</name2>
                </pair>
                <pair>
                    <name1>V0</name1>
                    <name2>V3</name2>
                </pair>
                <pair>
                    <name1>V2</name1>
                    <name2>V1</name2>
                </pair>
                <pair>
                    <name1>V2</name1>
                    <name2>V3</name2>
                </pair>
            </pairs>
        </group>
  	</Exchange>
  	<Anisotropy>
  		<group>
  			<name>Daz</name>
  			<value>0.8</value>
  			<direction>
  				<x>0.0</x>
  				<y>0.0</y>
  				<z>1.0</z>
  			</direction>
  			<sublattices>
  				<name>Mn0</name>
  				<name>Mn1</name>
  			</sublattices>
  		</group>
  		<group>
  		  	<name>Dbx</name>
  			<value>-6.351</value>
  			<direction>
  				<x>1.0</x>
  				<y>0.0</y>
  				<z>-1.0</z>
  			</direction>
  			<sublattices>
  				<name>V1</name>
  			</sublattices>
  		</group>
        <group>
  		  	<name>Dbmx</name>
  			<value>-6.351</value>
  			<direction>
  				<x>-1.0</x>
  				<y>0.0</y>
  				<z>-1.0</z>
  			</direction>
  			<sublattices>
  				<name>V3</name>
  			</sublattices>
  		</group>
  		<group>
  		  	<name>Dby</name>
  			<value>-6.351</value>
  			<direction>
  				<x>0.0</x>
  				<y>1.0</y>
  				<z>-1.0</z>
  			</direction>
  			<sublattices>
  				<name>V2</name>
  			</sublattices>
  		</group>
  		<group>
  		  	<name>Dbmy</name>
  			<value>-6.351</value>
  			<direction>
  				<x>0.0</x>
  				<y>-1.0</y>
  				<z>-1.0</z>
  			</direction>
  			<sublattices>
  				<name>V0</name>
  			</sublattices>
  		</group>
  	</Anisotropy>
  </interactions>
</spinwavegenie>

=== NickDraper/SpinWaveGenie/examples/old/MnF2.xml
<?xml version="1.0" encoding="UTF-8"?>
<spinwavegenie xmlns:swg="SpinWaveGenieSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="SpinWaveGenieSchema SpinWaveGenieSchema.xsd ">
  <cell>
    <latticevectors>
      <a>4.873</a>
      <b>4.873</b>
      <c>3.130</c>
      <alpha>90.0</alpha>
      <beta>90.0</beta>
      <gamma>90.0</gamma>
    </latticevectors>
    <moments>
      <sublattice>
        <name>Mn0</name>
        <type>MN2</type>
        <moment>
          <magnitude>2.5</magnitude>
          <theta>0.0</theta>
          <phi>0.0</phi>
        </moment>
        <atomicpositions>
          <position>
            <x>0.0</x>
            <y>0.0</y>
            <z>0.0</z>
          </position>
        </atomicpositions>
      </sublattice>
      <sublattice>
      	<name>Mn1</name>
      	<type>MN2</type>
      	<moment>
      		<magnitude>2.5</magnitude>
      		<theta>180.0</theta>
      		<phi>0.0</phi>
      	</moment>
      	<atomicpositions>
      		<position>
      			<x>0.5</x>
      			<y>0.5</y>
      			<z>0.5</z>
      		</position>
      	</atomicpositions>
      </sublattice>
    </moments>
  </cell>
  <interactions>
    <Anisotropy>
      <group>
        <value>-0.064</value>
        <direction>
          <x>0.0</x>
          <y>0.0</y>
          <z>1.0</z>
        </direction>
        <sublattices>
          <name>Mn0</name>
          <name>Mn1</name>
        </sublattices>
      </group>
    </Anisotropy>
    <Exchange>
      <group>
        <value>-0.31</value>
        <mindist>3.7</mindist>
        <maxdist>3.9</maxdist>
        <pairs>
          <pair>
            <name1>Mn0</name1>
            <name2>Mn1</name2>
          </pair>
        </pairs>
      </group>
    </Exchange>
  </interactions>
</spinwavegenie>

=== NickDraper/SpinWaveGenie/examples/MnBiJ123.xml
<?xml version="1.0" encoding="UTF-8"?>
<spinwavegenie xmlns="SpinWaveGenieSchema" xmlns:swg="http://www.example.org/SpinWaveGenieSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="SpinWaveGenieSchema SpinWaveGenieSchema.xsd ">
  <cell>
    <latticevectors>
      <a>4.2827</a>
      <b>4.2827</b>
      <c>6.1103</c>
      <alpha>90.0</alpha>
      <beta>90.0</beta>
      <gamma>120.0</gamma>
    </latticevectors>
    <moments>
      <sublattice>
        <name>Spin0</name>
        <type>NONE</type>
        <moment>
          <magnitude>2.0</magnitude>
          <theta>0.0</theta>
          <phi>0.0</phi>
        </moment>
        <atomicpositions>
          <position>
            <x>0.0</x>
            <y>0.0</y>
            <z>0.0</z>
          </position>
          <position>
            <x>0.0</x>
            <y>0.0</y>
            <z>0.5</z>
          </position>
        </atomicpositions>
      </sublattice>
    </moments>    
  </cell>
  <interactions>
      <Exchange>
        <group>
            <name>J1</name>
            <value>-0.5046023E+01</value>
            <mindist>3.0</mindist>
            <maxdist>3.1</maxdist>
            <pairs>
                <pair><name1>Spin0</name1><name2>Spin0</name2></pair>
            </pairs>
        </group>
        <group>
            <name>J2</name>
            <value>0.2653977E+01</value>
            <mindist>4.2</mindist>
            <maxdist>4.3</maxdist>
            <pairs>
                <pair><name1>Spin0</name1><name2>Spin0</name2></pair>
            </pairs>
        </group>
        <group>
            <name>J3</name>
            <value>0.2107670E+01</value>
            <mindist>5.2</mindist>
            <maxdist>5.3</maxdist>
            <pairs>
                <pair><name1>Spin0</name1><name2>Spin0</name2></pair>
            </pairs>
        </group>
    </Exchange>
  </interactions>
  <dispersion>
      <filename>MyDispersion.txt</filename>
      <filetype>
          <printposition>1</printposition>
          <printfrequency>1</printfrequency>
          <printintensity>1</printintensity>
      </filetype>
      <lines>
          <group>
              <firstpoint>
                  <x>0.0</x>
                  <y>0.0</y>
                  <z>2.0</z>
              </firstpoint>
              <lastpoint>
                  <x>1.0</x>
                  <y>0.0</y>
                  <z>2.0</z>
              </lastpoint>
              <numberpoints>101</numberpoints>
          </group>
      </lines>
  </dispersion>
</spinwavegenie>
